# Site settings
title: SPiN NYC
email: trisha.hadley@gmail.com
description: "SPiN NYC Booking Form"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/spinpong
  - title: facebook
    url: https://www.facebook.com/SPiNNewYork
  - title: instagram
    url: http://instagram.com/spinnewyork

# Postal address (add as many lines as necessary)
address:
  - line: 48 E 23rd St
  - line: New York, NY 10010

# Build settings
markdown: kramdown
permalink: pretty
